"""
Remove icons unrelated to illustration work from resources/icons/.
Run from project root: python scripts/curate_icons.py
"""

import os
import sys

ICONS_DIR = os.path.join(os.path.dirname(__file__), "..", "resources", "icons")

# Prefixes/exact names of icons to DELETE (not useful for illustration workflows)
DELETE_PATTERNS = [
    # --- Finance / Currency ---
    "bitcoin",
    "banknote",
    "coins",
    "credit-card",
    "dollar-sign",
    "euro",
    "indian-rupee",
    "japanese-yen",
    "pound-sterling",
    "russian-ruble",
    "saudi-riyal",
    "swiss-franc",
    "turkish-lira",
    "piggy-bank",
    "wallet",
    "wallet-cards",
    "wallet-minimal",
    "receipt",
    "badge-cent",
    "badge-dollar-sign",
    "badge-euro",
    "badge-indian-rupee",
    "badge-japanese-yen",
    "badge-pound-sterling",
    "badge-russian-ruble",
    "badge-swiss-franc",
    "badge-turkish-lira",
    "percent",
    # --- Transportation ---
    "car",
    "car-front",
    "car-taxi-front",
    "cable-car",
    "bus",
    "bus-front",
    "truck",
    "truck-electric",
    "plane",
    "plane-landing",
    "plane-takeoff",
    "train-front",
    "train-front-tunnel",
    "train-track",
    "tram-front",
    "sailboat",
    "ship",
    "ship-wheel",
    "bicycle",
    "bike",
    "scooter",
    "tractor",
    "ambulance",
    "fire-truck",
    "fuel",
    "traffic-cone",
    "road-barrier",
    "rail-symbol",
    # --- Food & Drink ---
    "pizza",
    "burger",
    "sandwich",
    "salad",
    "soup",
    "beef",
    "fish",
    "shrimp",
    "egg",
    "egg-fried",
    "croissant",
    "cookie",
    "candy",
    "apple",
    "banana",
    "cherry",
    "grape",
    "lemon",
    "nut",
    "wheat",
    "wheat-off",
    "broccoli",
    "carrot",
    "corn",
    "bean",
    "vegan",
    "milk",
    "coffee",
    "cup-soda",
    "glass-water",
    "beer",
    "wine",
    "wine-off",
    "martini",
    "citrus",
    "popcorn",
    "popsicle",
    "ice-cream",
    "cake",
    "cake-slice",
    "candy-cane",
    "dessert",
    "utensils",
    "utensils-crossed",
    "chef-hat",
    "cooking-pot",
    "microwave",
    "refrigerator",
    # --- Medical / Health ---
    "syringe",
    "stethoscope",
    "pill",
    "pill-bottle",
    "tablets",
    "thermometer",
    "thermometer-sun",
    "thermometer-snowflake",
    "heart-pulse",
    "activity",
    "dna",
    "microscope",
    "test-tube",
    "test-tubes",
    "test-tube-diagonal",
    "cross",
    "first-aid",
    "bandage",
    "hospital",
    "ambulance",
    "crutch",
    "scan-heart",
    "radiation",
    "siren",
    # --- Devices / Consumer Electronics ---
    "smartphone",
    "smartphone-charging",
    "smartphone-nfc",
    "tablet",
    "tablet-smartphone",
    "tv",
    "tv-minimal",
    "tv-minimal-play",
    "monitor-check",
    "monitor-dot",
    "monitor-off",
    "laptop",
    "laptop-minimal",
    "laptop-minimal-check",
    "headphones",
    "headset",
    "earphones",
    "speaker",
    "audio-lines",
    "radio",
    "radio-receiver",
    "radio-tower",
    "projector",
    "camera",
    "camera-off",
    "switch-camera",
    "video",
    "video-off",
    "webcam",
    "videotape",
    "turntable",
    "gamepad",
    "gamepad-2",
    "joystick",
    "watch",
    "smartwatch",
    "microchip",
    "cpu",
    "memory-stick",
    "battery",
    "battery-charging",
    "battery-full",
    "battery-low",
    "battery-medium",
    "battery-warning",
    "usb",
    "hard-drive",
    "hard-drive-download",
    "hard-drive-upload",
    "server",
    "server-cog",
    "server-crash",
    "server-off",
    "router",
    "hub",
    "satellite",
    "satellite-dish",
    "touchpad",
    "touchpad-off",
    # --- Business / Office ---
    "briefcase",
    "briefcase-business",
    "briefcase-conveyor-belt",
    "briefcase-medical",
    "handshake",
    "presentation",
    "presentation-control",
    "chart-pie",
    "chart-bar",
    "chart-line",
    "chart-area",
    "chart-candlestick",
    "chart-column",
    "chart-gantt",
    "chart-network",
    "chart-scatter",
    "chart-spline",
    "chart-no-axes-pie",
    "chart-no-axes-column",
    "chart-no-axes-gantt",
    "chart-no-axes-combined",
    "badge",
    "badge-check",
    "badge-x",
    "badge-plus",
    "badge-minus",
    "badge-help",
    "badge-info",
    "badge-alert",
    "nfc",
    "touchpad",
    "id-card",
    "contact",
    "contact-round",
    "address-book",
    "calendar",
    "calendar-check",
    "calendar-check-2",
    "calendar-clock",
    "calendar-days",
    "calendar-fold",
    "calendar-heart",
    "calendar-minus",
    "calendar-minus-2",
    "calendar-off",
    "calendar-plus",
    "calendar-plus-2",
    "calendar-range",
    "calendar-search",
    "calendar-x",
    "calendar-x-2",
    "ticket",
    "ticket-check",
    "ticket-minus",
    "ticket-percent",
    "ticket-plus",
    "ticket-slash",
    "ticket-x",
    "tickets",
    "tickets-plane",
    "luggage",
    "backpack",
    "newspaper",
    "book-open-check",
    "book-copy",
    "book-dashed",
    "book-down",
    "book-headphones",
    "book-heart",
    "book-image",
    "book-key",
    "book-lock",
    "book-marked",
    "book-minus",
    "book-plus",
    "book-type",
    "book-up",
    "book-up-2",
    "book-user",
    "book-x",
    "book-a",
    "library",
    "books",
    "notepad-text",
    "notepad-text-dashed",
    "votes",
    "vote",
    "ballot-box",
    "award",
    "trophy",
    "medal",
    "handshake",
    # --- Social Media / Brands ---
    "twitter",
    "x",
    "slack",
    "twitch",
    "youtube",
    "trello",
    "gitlab",
    "github",
    "rss",
    "podcast",
    # --- Network / Infrastructure ---
    "wifi",
    "wifi-cog",
    "wifi-high",
    "wifi-low",
    "wifi-off",
    "wifi-pen",
    "wifi-sync",
    "wifi-zero",
    "bluetooth",
    "bluetooth-connected",
    "bluetooth-off",
    "bluetooth-searching",
    "network",
    "network-off",
    "globe",
    "globe-lock",
    "signal",
    "signal-high",
    "signal-low",
    "signal-medium",
    "signal-zero",
    "antenna",
    "tower-control",
    "webhook",
    "webhook-off",
    "voicemail",
    "phone",
    "phone-call",
    "phone-forwarded",
    "phone-incoming",
    "phone-missed",
    "phone-off",
    "phone-outgoing",
    "mail",
    "mail-check",
    "mail-minus",
    "mail-open",
    "mail-plus",
    "mail-question",
    "mail-search",
    "mail-warning",
    "mail-x",
    "at-sign",
    "inbox",
    "send-horizontal",
    # --- Buildings / Places ---
    "building",
    "building-2",
    "house",
    "home",
    "warehouse",
    "factory",
    "store",
    "school",
    "university",
    "hospital",
    "hotel",
    "church",
    "castle",
    "landmark",
    "tent",
    "tent-tree",
    "tree-deciduous",
    "tree-palm",
    "tree-pine",
    "trees",
    "sprout",
    "shrub",
    # --- Weather ---
    "cloud",
    "cloud-drizzle",
    "cloud-fog",
    "cloud-hail",
    "cloud-lightning",
    "cloud-moon",
    "cloud-moon-rain",
    "cloud-off",
    "cloud-rain",
    "cloud-rain-wind",
    "cloud-snow",
    "cloud-sun",
    "cloud-sun-rain",
    "cloud-upload",
    "cloud-download",
    "cloud-cog",
    "cloud-alert",
    "sun",
    "sun-dim",
    "sun-medium",
    "sun-moon",
    "sun-snow",
    "sunrise",
    "sunset",
    "moon",
    "moon-star",
    "snowflake",
    "rainbow",
    "wind",
    "wind-arrow-down",
    "tornado",
    "cloudy",
    "hurricane",
    # --- Sports ---
    "dumbbell",
    "volleyball",
    "football",
    "golf",
    "bike",
    "bicycle",
    "roller-coaster",
    "skateboard",
    "tennis",
    "medal",
    # --- Animals ---
    "dog",
    "cat",
    "bird",
    "fish",
    "rabbit",
    "rat",
    "snail",
    "squirrel",
    "turtle",
    "worm",
    "bug",
    "bug-off",
    "bug-play",
    # --- Clothing / Personal ---
    "shirt",
    "glasses",
    "sunglasses",
    "hat",
    "shopping-bag",
    "shopping-basket",
    "shopping-cart",
    # --- Household ---
    "sofa",
    "rocking-chair",
    "toilet",
    "shower-head",
    "bath",
    "lamp",
    "lamp-ceiling",
    "lamp-desk",
    "lamp-floor",
    "lamp-wall-down",
    "lamp-wall-up",
    "washing-machine",
    "refrigerator",
    "microwave",
    "air-vent",
    "heater",
    "fan",
    "door-open",
    "door-closed",
    "key-round",
    "key-square",
    # --- Misc unrelated ---
    "skull",
    "ghost",
    "halloween",
    "party-popper",
    "rocket",
    "planet",
    "satellite",
    "cigarette",
    "cigarette-off",
    "beer",
    "beer-off",
    "baby",
    "footprints",
    "dog-off",
    "handshake",
    "heart-handshake",
    "map",
    "map-pin",
    "map-pin-check",
    "map-pin-check-inside",
    "map-pin-house",
    "map-pin-minus",
    "map-pin-off",
    "map-pin-plus",
    "map-pin-x",
    "map-pinned",
    "map-off",
    "navigation",
    "navigation-off",
    "compass",
    "flag",
    "flag-off",
    "flag-triangle-left",
    "flag-triangle-right",
    "signpost",
    "signpost-big",
    "fuel",
    "gauge",
    "shovel",
    "pickaxe",
    "hammer-off",
    "drill",
    "anvil",
    "axe",
    "siren",
    "alarm-clock",
    "alarm-clock-check",
    "alarm-clock-minus",
    "alarm-clock-off",
    "alarm-clock-plus",
    "clock",
    "clock-1",
    "clock-2",
    "clock-3",
    "clock-4",
    "clock-5",
    "clock-6",
    "clock-7",
    "clock-8",
    "clock-9",
    "clock-10",
    "clock-11",
    "clock-12",
    "clock-alert",
    "history",
    "timer",
    "timer-off",
    "timer-reset",
    "hourglass",
    "bed",
    "bed-double",
    "bed-single",
]


def should_delete(filename: str) -> bool:
    name = filename.replace(".svg", "")
    for pattern in DELETE_PATTERNS:
        if name == pattern or name.startswith(pattern + "-") or name.startswith(pattern + "_"):
            return True
    return False


def main():
    if not os.path.isdir(ICONS_DIR):
        print(f"Icons dir not found: {ICONS_DIR}")
        sys.exit(1)

    files = [f for f in os.listdir(ICONS_DIR) if f.endswith(".svg")]
    to_delete = [f for f in files if should_delete(f)]
    to_keep = [f for f in files if not should_delete(f)]

    print(f"Total: {len(files)}  |  Delete: {len(to_delete)}  |  Keep: {len(to_keep)}")

    if "--dry-run" in sys.argv:
        print("\n[DRY RUN] Would delete:")
        for f in sorted(to_delete):
            print(f"  {f}")
        return

    for f in to_delete:
        os.remove(os.path.join(ICONS_DIR, f))

    print(f"Deleted {len(to_delete)} icons. {len(to_keep)} remain.")


if __name__ == "__main__":
    main()
